### ISSUE TITLE
About the testing results on Dataset #1

### ISSUE THREAD

**Issue by Li-Zhaoxi** [dlut-dimt/ellipse-detector#1]
I used the CNED.exe in the file "Demo" to evaluate your method On dataset #1.  The testing result F-measure was 0.460453, which was different from the result 0.5955 in your paper. Could you tell me how can I get the similiar result of your paper?

Note: The detection results on Dataset #1 by CNED.exe.

picName | F-measure | countsOfFindEllipse | countsOfGetFastCenter
-- | -- | -- | --
00004.jpg | 0 | 13 | 84
00023.jpg | 0.222222 | 8 | 75
00058.jpg | 1 | 3 | 19
00155.jpg | 0 | 2 | 8
00409.jpg | 0 | 0 | 0
00414.jpg | 0.5 | 12 | 40
00640.jpg | 0 | 0 | 8
01210.jpg | 0 | 0 | 3
01295.jpg | 0.4 | 11 | 25
01720.jpg | 1 | 4 | 14
0187.jpg | 0.666667 | 19 | 614
04734.jpg | 0.666667 | 5 | 16
04936.jpg | 0.666667 | 11 | 15
05093.jpg | 1 | 5 | 19
0524.jpg | 0.769231 | 76 | 621
0757.jpg | 0.5 | 16 | 444
0796.jpg | 0 | 9 | 46
0859.jpg | 1 | 3 | 116
8000112.jpg | 1 | 12 | 36
Hda_obj1.jpg | 0.5 | 35 | 54
Hda_obj357.jpg | 1 | 3 | 10
Hda_obj47.jpg | 0.25 | 37 | 236
Hda_obj5.jpg | 0 | 3 | 13
Hda_obj93.jpg | 1 | 1 | 2
Hda_obj95.jpg | 0.4 | 536 | 180
Hda_obj98.jpg | 0.666667 | 4 | 13
IMG_0796.jpg | 0.4 | 18 | 447
U0987_0000.jpg | 0.571429 | 87 | 795
U1024_0000.jpg | 0 | 10 | 192
a379017.jpg | 0.666667 | 10 | 45
art359.jpg | 0 | 1 | 4
at_04_02_3000_09_l.jpg | 0 | 4 | 8
b3.jpg | 0 | 1 | 3
bath244.jpg | 1 | 23 | 29
bath98.jpg | 0 | 0 | 14
bike_0001.jpg | 0.571429 | 32 | 480
bike_0002.jpg | 0.2 | 395 | 946
bike_0003.jpg | 0.545455 | 89 | 708
bike_0004.jpg | 0.363636 | 67 | 573
bike_0005.jpg | 0.555556 | 85 | 728
bike_0006.jpg | 0.533333 | 236 | 668
bike_0007.jpg | 0 | 17 | 746
bike_0008.jpg | 0.428571 | 145 | 1154
bike_0009.jpg | 0.461538 | 209 | 1108
bike_0010.jpg | 0.571429 | 216 | 686
bike_0011.jpg | 0.375 | 118 | 838
bike_0012.jpg | 0.666667 | 43 | 596
bike_0013.jpg | 0.421053 | 292 | 899
bike_0014.jpg | 0.888889 | 41 | 361
bike_0015.jpg | 0.588235 | 146 | 634
bike_0016.jpg | 0.352941 | 286 | 805
bike_0017.jpg | 0.4 | 136 | 617
bike_0018.jpg | 0.714286 | 61 | 489
bike_0019.jpg | 0.666667 | 170 | 674
bike_0020.jpg | 0.476191 | 199 | 594
bike_0021.jpg | 0.380952 | 435 | 1476
bike_0061.jpg | 0.666667 | 88 | 398
bike_0062.jpg | 0.461538 | 126 | 414
bike_0063.jpg | 0.315789 | 137 | 1918
bike_0064.jpg | 0.285714 | 39 | 415
bike_0065.jpg | 0.228571 | 782 | 2436
bike_0066.jpg | 0.444444 | 57 | 454
bike_0067.jpg | 0.32 | 221 | 2092
bike_0068.jpg | 0.545455 | 74 | 415
bike_0069.jpg | 0.470588 | 109 | 580
bike_0070.jpg | 0.428571 | 85 | 467
bike_0071.jpg | 0.363636 | 58 | 787
bike_0072.jpg | 0.307692 | 132 | 404
bike_0073.jpg | 0.533333 | 56 | 644
bike_0074.jpg | 0.428571 | 120 | 1691
bike_0075.jpg | 0.421053 | 173 | 1575
bike_0076.jpg | 0.4 | 26 | 341
bike_0077.jpg | 0.333333 | 350 | 1522
bike_0078.jpg | 0.545455 | 60 | 978
bike_0079.jpg | 0.181818 | 217 | 1916
bike_0080.jpg | 0.421053 | 394 | 1250
bike_0081.jpg | 0.363636 | 143 | 1874
boston145.jpg | 0.666667 | 1 | 68
cannon_0001.jpg | 0.25 | 16 | 321
cannon_0002.jpg | 0.666667 | 11 | 48
cannon_0003.jpg | 0 | 6 | 217
cannon_0004.jpg | 0.222222 | 6 | 80
cannon_0005.jpg | 0.666667 | 9 | 69
cannon_0006.jpg | 0.461538 | 35 | 390
cannon_0007.jpg | 0.2 | 50 | 890
cannon_0008.jpg | 0 | 2 | 9
cannon_0009.jpg | 0 | 9 | 81
cannon_0010.jpg | 0.333333 | 2 | 42
cannon_0011.jpg | 0.526316 | 32 | 276
cannon_0013.jpg | 1 | 5 | 23
cannon_0014.jpg | 0 | 0 | 0
cannon_0015.jpg | 0.3 | 219 | 1986
cannon_0018.jpg | 0 | 1 | 42
cannon_0019.jpg | 0.5 | 21 | 236
cannon_0048.jpg | 0.666667 | 3 | 36
cannon_0050.jpg | 0 | 0 | 8
cannon_0051.jpg | 0 | 0 | 6
cannon_0055.jpg | 0.5 | 4 | 19
cannon_0059.jpg | 0.4 | 2 | 19
cimg1239.jpg | 0.4 | 62 | 3658
cimg1250.jpg | 0.4 | 244 | 5278
cimg1291.jpg | 0.210526 | 259 | 4172
cimg1295.jpg | 0.27907 | 462 | 4222
cimg1297.jpg | 0.246154 | 938 | 8394
cimg1309.jpg | 0.230769 | 402 | 2660
conference8.jpg | 0.142857 | 20 | 410
conferenceroom3.jpg | 0 | 0 | 0
couloir_ch1_5e.jpg | 0.4 | 4 | 10
dsc04339.jpg | 0.222222 | 161 | 2012
ellipse6.jpg | 1 | 4 | 4
enc36.jpg | 1 | 5 | 25
im100331.jpg | 0.153846 | 113 | 233
im100398.jpg | 0 | 7 | 207
im100424.jpg | 0.4 | 22 | 273
im100428.jpg | 0.666667 | 61 | 607
im100443.jpg | 0.222222 | 21 | 330
im100457.jpg | 0 | 6 | 106
im100490.jpg | 0.428571 | 172 | 1186
im100628.jpg | 1 | 81 | 563
im100670.jpg | 0.5 | 15 | 80
im100719.jpg | 0.285714 | 52 | 244
im100729.jpg | 0.666667 | 8 | 11
im100752.jpg | 0.4 | 12 | 265
im100792.jpg | 0.666667 | 48 | 211
im100830.jpg | 0.285714 | 51 | 154
im100861.jpg | 0.333333 | 37 | 617
im100939.jpg | 0.5 | 89 | 122
im100972.jpg | 0.4 | 42 | 221
im101042.jpg | 0.666667 | 121 | 674
im101098.jpg | 0.666667 | 52 | 173
im101107.jpg | 0.2 | 107 | 364
im101156.jpg | 0 | 0 | 17
im101295.jpg | 0.666667 | 49 | 348
im102084.jpg | 0.666667 | 43 | 123
im102091.jpg | 0.5 | 31 | 166
im102094.jpg | 1 | 11 | 60
im102174.jpg | 0.5 | 9 | 238
im102289.jpg | 0 | 18 | 217
im102318.jpg | 0.4 | 37 | 334
im102428.jpg | 0.6 | 67 | 409
im102474.jpg | 1 | 29 | 123
im102561.jpg | 0.6 | 63 | 359
im102694.jpg | 0.666667 | 5 | 118
im102728.jpg | 0.26087 | 114 | 466
im102835.jpg | 0 | 0 | 14
im102906.jpg | 0.333333 | 388 | 699
im103246.jpg | 0.5 | 27 | 283
im103254.jpg | 0 | 0 | 209
im103707.jpg | 0 | 21 | 359
im103904.jpg | 1 | 19 | 635
im104124.jpg | 1 | 8 | 117
im104300.jpg | 0.533333 | 116 | 601
im104494.jpg | 0.666667 | 3 | 15
im104577.jpg | 0.333333 | 16 | 199
im104580.jpg | 0.333333 | 38 | 120
im104601.jpg | 0.8 | 30 | 87
im104764.jpg | 0.25 | 21 | 182
im104878.jpg | 0.571429 | 93 | 430
im104984.jpg | 1 | 6 | 48
im105216.jpg | 0.285714 | 40 | 294
im105222.jpg | 0 | 8 | 150
im105256.jpg | 0.25 | 120 | 199
im105288.jpg | 1 | 5 | 15
im1053.jpg | 0.434783 | 185 | 868
im105799.jpg | 0.5 | 43 | 79
im106879.jpg | 1 | 10 | 63
im107074.jpg | 0.4 | 25 | 167
im107107.jpg | 0.666667 | 28 | 190
im1086.jpg | 0.8 | 57 | 524
im108844.jpg | 0.25 | 37 | 111
im109208.jpg | 0.571429 | 29 | 132
im110368.jpg | 0.571429 | 83 | 243
im110474.jpg | 0.5 | 19 | 88
im110490.jpg | 0.571429 | 351 | 933
im110636.jpg | 0.666667 | 6 | 93
im110815.jpg | 0 | 2 | 100
im110822.jpg | 0.5 | 42 | 200
im110946.jpg | 0.5 | 9 | 42
im111036.jpg | 1 | 4 | 12
im111097.jpg | 1 | 8 | 29
im111950.jpg | 1 | 13 | 244
im112075.jpg | 0 | 15 | 337
im112110.jpg | 0.8 | 44 | 361
im112635.jpg | 0.4 | 151 | 437
im113622.jpg | 0.666667 | 5 | 52
im113861.jpg | 0.666667 | 14 | 91
im114409.jpg | 1 | 7 | 63
im114628.jpg | 0 | 52 | 447
im115119.jpg | 0.666667 | 2 | 9
im116832.jpg | 0.333333 | 242 | 1225
im116838.jpg | 0.666667 | 22 | 150
im116861.jpg | 1 | 78 | 317
im117199.jpg | 0.410256 | 55 | 580
im117386.jpg | 0.285714 | 76 | 441
im117389.jpg | 1 | 71 | 262
im117634.jpg | 0.666667 | 6 | 22
im117736.jpg | 0.2 | 144 | 206
im117751.jpg | 0 | 2 | 51
im118026.jpg | 0.5 | 75 | 122
im118081.jpg | 0.4 | 31 | 235
im118124.jpg | 0 | 0 | 2
im118256.jpg | 0.8 | 32 | 71
im118290.jpg | 0.444444 | 32 | 291
im118300.jpg | 0 | 0 | 6
im119299.jpg | 1 | 8 | 85
im119755.jpg | 1 | 12 | 113
im1227.jpg | 0.8 | 65 | 112
im128.jpg | 1 | 5 | 28
im1283.jpg | 0.4 | 52 | 127
im1287.jpg | 0.285714 | 29 | 104
im1377.jpg | 0.25 | 171 | 353
im1382.jpg | 0.8 | 36 | 368
im1433.jpg | 0.444444 | 201 | 594
im1471.jpg | 0.666667 | 3 | 71
im149.jpg | 0.444444 | 176 | 532
im150.jpg | 0 | 5 | 56
im152.jpg | 0 | 1 | 17
im1557.jpg | 0.4 | 149 | 639
im1561.jpg | 0.545455 | 107 | 404
im1612.jpg | 0.181818 | 17 | 389
im1614.jpg | 0.666667 | 7 | 124
im1626.jpg | 0.888889 | 33 | 342
im1689.jpg | 0.571429 | 193 | 234
im1787.jpg | 0.363636 | 56 | 324
im183.jpg | 0 | 6 | 105
im186.jpg | 0 | 6 | 94
im1881.jpg | 0.4 | 21 | 88
im1899.jpg | 0 | 6 | 164
im1922.jpg | 1 | 10 | 46
im1937.jpg | 0.363636 | 172 | 196
im1976.jpg | 0.285714 | 30 | 198
im1991.jpg | 0.444444 | 28 | 426
im2032.jpg | 0.666667 | 4 | 78
im2062.jpg | 0.428571 | 135 | 1552
im2277.jpg | 1 | 10 | 32
im2284.jpg | 0 | 0 | 200
im2307.jpg | 0.222222 | 35 | 379
im2520.jpg | 1 | 6 | 72
im2548.jpg | 0.444444 | 21 | 80
im256.jpg | 0 | 0 | 76
im2562.jpg | 0 | 8 | 547
im2576.jpg | 0.666667 | 4 | 33
im2649.jpg | 0.5 | 85 | 540
im2670.jpg | 0.5 | 104 | 333
im270.jpg | 0 | 0 | 54
im2717.jpg | 0.571429 | 26 | 242
im280.jpg | 0 | 1 | 24
im2899.jpg | 0 | 4 | 148
im29.jpg | 0.5 | 251 | 610
im2907.jpg | 1 | 20 | 317
im2916.jpg | 0.285714 | 48 | 525
im2925.jpg | 0.5 | 8 | 111
im2954.jpg | 0.4 | 13 | 42
im2956.jpg | 0 | 12 | 212
im2968.jpg | 1 | 5 | 26
im3024.jpg | 0.666667 | 27 | 575
im304.jpg | 0.222222 | 64 | 1054
im3069.jpg | 0 | 1 | 60
im3090.jpg | 1 | 4 | 9
im3126.jpg | 1 | 26 | 224
im3129.jpg | 0.6 | 39 | 354
im3228.jpg | 0.28 | 284 | 2670
im323.jpg | 0 | 8 | 337
im325.jpg | 0.571429 | 32 | 89
im3353.jpg | 0.4 | 18 | 122
im3366.jpg | 1 | 15 | 140
im3375.jpg | 0.333333 | 78 | 331
im3420.jpg | 0.285714 | 20 | 277
im343.jpg | 0 | 9 | 86
im3457.jpg | 0.571429 | 43 | 122
im3485.jpg | 0.5 | 6 | 50
im3507.jpg | 0.666667 | 7 | 68
im355.jpg | 0.5 | 17 | 100
im357.jpg | 0.444444 | 41 | 203
im3588.jpg | 0 | 8 | 83
im3597.jpg | 0.8 | 35 | 172
im3611.jpg | 0.444444 | 47 | 125
im366.jpg | 0.4 | 10 | 166
im371.jpg | 0.5 | 36 | 796
im382.jpg | 0 | 5 | 218
im3822.jpg | 0.8 | 54 | 172
im3826.jpg | 0 | 30 | 171
im3914.jpg | 1 | 4 | 7
im393.jpg | 0.5 | 292 | 1167
im3947.jpg | 0.571429 | 35 | 174
im3949.jpg | 0.666667 | 84 | 295
im3957.jpg | 0.666667 | 27 | 234
im398.jpg | 0.8 | 88 | 352
im4005.jpg | 0.666667 | 7 | 121
im401.jpg | 0.545455 | 57 | 411
im402.jpg | 0 | 8 | 398
im411.jpg | 0.5 | 25 | 570
im4175.jpg | 0.5 | 14 | 207
im4197.jpg | 0.666667 | 2 | 34
im4200.jpg | 0 | 1 | 122
im423.jpg | 0.307692 | 120 | 370
im4231.jpg | 0 | 0 | 3
im4295.jpg | 0.4 | 7 | 243
im4332.jpg | 0.75 | 73 | 105
im4378.jpg | 0.285714 | 16 | 276
im4401.jpg | 1 | 2 | 20
im444.jpg | 0.666667 | 5 | 140
im4457.jpg | 0.571429 | 20 | 257
im4477.jpg | 0.5 | 18 | 145
im4483.jpg | 0.8 | 34 | 48
im451.jpg | 0.666667 | 8 | 232
im4511.jpg | 0 | 7 | 130
im455.jpg | 0 | 0 | 13
im4571.jpg | 0.666667 | 37 | 77
im4595.jpg | 0.428571 | 246 | 655
im462.jpg | 0.25 | 30 | 164
im463.jpg | 0.333333 | 32 | 451
im475.jpg | 1 | 48 | 202
im492.jpg | 0.666667 | 24 | 57
im494.jpg | 0.571429 | 67 | 870
im4960.jpg | 0.5 | 147 | 498
im5031.jpg | 1 | 4 | 9
im518.jpg | 0.5 | 24 | 474
im5479.jpg | 0.5 | 96 | 201
im5783.jpg | 0.333333 | 27 | 150
im5799.jpg | 1 | 4 | 9
im5882.jpg | 1 | 1 | 2
im596.jpg | 0.666667 | 37 | 186
im6017.jpg | 1 | 8 | 201
im6019.jpg | 0.266667 | 87 | 1473
im6054.jpg | 0.4 | 25 | 754
im6059.jpg | 0.4 | 38 | 246
im6106.jpg | 0.25 | 21 | 455
im6117.jpg | 0.666667 | 10 | 70
im6185.jpg | 0.5 | 40 | 66
im6503.jpg | 0.666667 | 99 | 123
im6562.jpg | 0 | 4 | 237
im6572.jpg | 0.571429 | 56 | 294
im6667.jpg | 0.375 | 68 | 688
im6779.jpg | 0.666667 | 26 | 113
im6842.jpg | 1 | 12 | 21
im688.jpg | 0.666667 | 12 | 50
im6987.jpg | 0.666667 | 16 | 81
im7017.jpg | 1 | 13 | 38
im7199.jpg | 0 | 41 | 271
im7554.jpg | 0.666667 | 6 | 105
im7579.jpg | 0.666667 | 45 | 193
im7624.jpg | 0.210526 | 34 | 275
im7671.jpg | 0.857143 | 26 | 41
im7703.jpg | 0.5 | 9 | 251
im7707.jpg | 0.666667 | 20 | 75
im7832.jpg | 0 | 10 | 195
im792.jpg | 1 | 17 | 24
im7988.jpg | 0.571429 | 73 | 153
im811.jpg | 0.5 | 54 | 271
im8127.jpg | 0.333333 | 44 | 152
im8129.jpg | 0.666667 | 30 | 210
im8130.jpg | 1 | 7 | 117
im8221.jpg | 0.5 | 12 | 283
im8237.jpg | 0.727273 | 53 | 72
im827.jpg | 0 | 13 | 167
im8367.jpg | 0.307692 | 36 | 403
im8369.jpg | 0.333333 | 11 | 71
im84.jpg | 0 | 2 | 67
im8415.jpg | 0.5 | 33 | 306
im8419.jpg | 0 | 1 | 95
im8445.jpg | 1 | 11 | 109
im8735.jpg | 1 | 8 | 135
im8833.jpg | 0.5 | 79 | 337
im887.jpg | 0.5 | 53 | 81
im8980.jpg | 0.5 | 19 | 65
im8982.jpg | 0.4 | 105 | 566
im9.jpg | 0.333333 | 3 | 18
im9185.jpg | 0.4 | 37 | 120
im922.jpg | 0.428571 | 61 | 1055
im923.jpg | 0.181818 | 11 | 140
im9288.jpg | 0.444444 | 49 | 151
im9368.jpg | 0.545455 | 231 | 1128
im9370.jpg | 0.571429 | 76 | 315
im9409.jpg | 0.8 | 36 | 201
im9551.jpg | 0 | 5 | 47
im961.jpg | 0.75 | 26 | 97
im9658.jpg | 0.333333 | 31 | 173
im9659.jpg | 0.666667 | 7 | 144
im9665.jpg | 0.5 | 11 | 501
im967.jpg | 0.5 | 119 | 617
im9852.jpg | 0.666667 | 172 | 605
im9882.jpg | 0.615385 | 191 | 1498
im993.jpg | 1 | 18 | 69
ins24.jpg | 1 | 4 | 26
insidecity_a212052.jpg | 0 | 1 | 12
insidecity_a385075.jpg | 0 | 2 | 59
insidecity_a855084.jpg | 0 | 1 | 4
insidecity_art1366.jpg | 0 | 0 | 2
int188.jpg | 0 | 3 | 26
ncupnpaint05.jpg | 0.333333 | 42 | 1245
nef1.jpg | 0 | 0 | 6
or_04_04_0007_29_l.jpg | 0.666667 | 5 | 30
people156.jpg | 0 | 3 | 45
sa_97_1_699_21_l.jpg | 0 | 1 | 8
slobby21.jpg | 0.75 | 26 | 33
slobby23.jpg | 0 | 2 | 8
tallbuilding_urban158.jpg | 0 | 0 | 0
tv759.jpg | 0 | 2 | 19
va_05_02_8100_02_l.jpg | 0 | 0 | 6
average | 0.460453 | 58.0275 | 380.77

**Comment by NeilXieTian** [comment]
Could you please tell me how you ran CNDE.exe on Windows 10 or a 32bit OS? When I started the demo, it always gave me the error message that "the program can not be started(0xc0000142)".

**Comment by Li-Zhaoxi** [comment]
@NeilXieTian I have installed the VS2015, and copy the "opencv_core249.dll, opencv_highgui249.dll, opencv_imgproc249.dll" from the file "build/x86/vc12" of "opencv 2.4.9".

I gauss that the author maybe used the VS2012/VS2013 with opencv2.4.9, and built this 32 bit CNED.exe

By the way, if you can run the same result with this paper, please contact me. My email is "lizhaoxi@buaa.edu.cn" and wechat number is "1084698040". Thank you very much!

**Comment by xiahaa** [comment]
> @NeilXieTian I have installed the VS2015, and copy the "opencv_core249.dll, opencv_highgui249.dll, opencv_imgproc249.dll" from the file "build/x86/vc12" of "opencv 2.4.9".
> 
> I gauss that the author maybe used the VS2012/VS2013 with opencv2.4.9, and built this 32 bit CNED.exe
> 
> By the way, if you can run the same result with this paper, please contact me. My email is "[lizhaoxi@buaa.edu.cn](mailto:lizhaoxi@buaa.edu.cn)" and wechat number is "1084698040". Thank you very much!

Hi, I met the same issue. It seems this algorithm is sensitive to the parameters used. With the code provided, it is not possible to reproduce the results proposed in the paper, neither can I reproduce the results in the sample image.

Have you figured out a solution?

**Comment by mrliuxx** [comment]
@NeilXieTian @Li-Zhaoxi Hi, I hava installed VS2019, and used the OpenCV 3.47 lib, successfully ran the source code. When you use OpenCV 2.x version, you need core, highgui and imgproc three Dll to run exe program, but I guess 3.x version does not need. 

If you use the source code to build the VS project, and configure the OpenCV link library, you can generate a new executable exe program. Of course, to run Demo or the new exe program, the correct `Microsoft Visual C ++` library is necessary. It is recommended that you use the official `Microsoft Visual Studio Installer` software to perfect your computer.

**Comment by mrliuxx** [comment]
@Li-Zhaoxi @xiahaa Hi, I met the same issue, but I used other methods to reproduce the similar results. I think there are two main factors that affect the F-m results. First, is the form of the ellipse parameter in Ground Truth consistent with the form of the detected ellipse parameter? For example, the range of the deflection angle, the radian system or the angle system. When reading the parameters of the two parts in the evaluation method, have you ensured that they have the same form? Secondly, there are two ways to calculate the F-m value, accumulate the F-m of each picture and take the average, or accumulate the TP, FP and FN of each picture and then calculate the F-m.

The first way of calculating F-m is used in the source code, and we can't get similar results. I guess it is because the form of the parameters is inconsistent. So I unified the parameter form of GT and Test, and used the second method to calculate F-m, then got a similar result with this paper.

If you still have questions about these, please contact me, I can provide you with the normalized GT parameters and evaluation method codes. My email is "[xuxuliu77@163.com](url)" and QQ number is "[1650708445](url)".

**Comment by xiahaa** [comment]
> @Li-Zhaoxi @xiahaa Hi, I met the same issue, but I used other methods to reproduce the similar results. I think there are two main factors that affect the F-m results. First, is the form of the ellipse parameter in Ground Truth consistent with the form of the detected ellipse parameter? For example, the range of the deflection angle, the radian system or the angle system. When reading the parameters of the two parts in the evaluation method, have you ensured that they have the same form? Secondly, there are two ways to calculate the F-m value, accumulate the F-m of each picture and take the average, or accumulate the TP, FP and FN of each picture and then calculate the F-m.
> 
> The first way of calculating F-m is used in the source code, and we can't get similar results. I guess it is because the form of the parameters is inconsistent. So I unified the parameter form of GT and Test, and used the second method to calculate F-m, then got a similar result with this paper.
> 
> If you still have questions about these, please contact me, I can provide you with the normalized GT parameters and evaluation method codes. My email is "[xuxuliu77@163.com](url)" and QQ number is "[1650708445](url)".

Thanks for your reply.
I am not following this work right now since I found some inconsistencies with their TIP paper in the code. I list my questions [here](https://github.com/dlut-dimt/ellipse-detector/issues/4).
In short, they seem not to use line prune in their code, but they mentioned this point in the paper.
For conic prune, they mention only sth like doing prune based on I and II, as well as II and III quadrants. However, in the code, they do this for all combinations....

Because of those points, I am thinking that the exe file should be ok, but the source code may be an experimental version that someone needs to tune a little bit to get a similar result (hopefully).

**Comment by mrliuxx** [comment]
@xiahaa Yes, I agree with your first point. Maybe this code is an experimental version, and someone needs to tune a little bit to get a similar result (That's what i did). I guess the same reason makes line pruning commented. But about conic prune, I insist on my opinion.
