### ISSUE TITLE
several issues not matched with the TIP paper

### ISSUE THREAD

**Issue by xiahaa** [dlut-dimt/ellipse-detector#4]
Hi, thanks for providing the source code. 
May I ask a few questions regarding this code and the TIP paper.
1. it mentioned in the paper that edges similar to lines will be pruned by using the CN line score. However, in the provided code, both DISCARD_TCN1 and DISCARD_TCN MACROS have been defined. So this means the line prune will not be executed. 
2. about using CN conic for filtering out edge tuples not on the same conic. In the paper, it mentions that you will use the first, the median, and the last points of I+II or II+III to compute the CN conic score. However, according to the code,
firstly,
> #define T124 pjf,pjm,pjl,pif,pim,pil //原来的

then
> #define V2SP Point2f p3,Point2f p2,Point2f p1,Point2f p4,Point2f p5,Point2f p6

then actually, you use the first and median points of one edge to compute l1 and then the last and the first point of another edge to compute l2. Finally, the conic score. This doesn't match with section III C in your TIP paper. Is there something wrong? Or I understood wrongly.

May you have time, could you please answer those questions.
Thanks again.

**Comment by mrliuxx** [comment]
@xiahaa Hi, regarding your second question, I think the code is correct. I don't understand what you said to use two points to calculate "l1" or "l2" respectively. You have doubts about using CN conic for filtering out edge tuples not on the same conic. I guess the doubts are in the code's `Triplets124(), Triplets231(), Triplets231(), Triplets342()` functions. I can tell you my understanding of them, taking the `Triplets124()` function as an example.

First, the arc set `pi, pj, pk` of the three quadrants is used as the method parameter; Then select an arc `edge_i` in `pi`, take its endpoint and midpoint to form three points `pif, pim, pil`; And also take the `edge_j` in `pj` three points `pjf, pjm, pjl`, they constitute `T124`. In the `value4SixPoints()` function, CN conic is calculated, and the six points of `T124` are respectively assigned to the six points `p3 ... p6` of `V2SP`. This is the calculation between the inner arcs of the quadrants `i` and `j`. The same method is used to calculate the quadrants `i` and `k`, and the quadrants `j` and `k`.

This matches with section III C in the TIP paper. If you have other questions, please contact me. My email is "[xuxuliu77@163.com](url)" and QQ number is "[1650708445](url)".

**Comment by xiahaa** [comment]
> @xiahaa Hi, regarding your second question, I think the code is correct. I don't understand what you said to use two points to calculate "l1" or "l2" respectively. You have doubts about using CN conic for filtering out edge tuples not on the same conic. I guess the doubts are in the code's `Triplets124(), Triplets231(), Triplets231(), Triplets342()` functions. I can tell you my understanding of them, taking the `Triplets124()` function as an example.
> 
> First, the arc set `pi, pj, pk` of the three quadrants is used as the method parameter; Then select an arc `edge_i` in `pi`, take its endpoint and midpoint to form three points `pif, pim, pil`; And also take the `edge_j` in `pj` three points `pjf, pjm, pjl`, they constitute `T124`. In the `value4SixPoints()` function, CN conic is calculated, and the six points of `T124` are respectively assigned to the six points `p3 ... p6` of `V2SP`. This is the calculation between the inner arcs of the quadrants `i` and `j`. The same method is used to calculate the quadrants `i` and `k`, and the quadrants `j` and `k`.
> 
> This matches with section III C in the TIP paper. If you have other questions, please contact me. My email is "[xuxuliu77@163.com](url)" and QQ number is "[1650708445](url)".

take t124 for example:
`pjf, pjm, pjl` should be the first, median, last point of segment in quadrant II.
`pif, pim, pil` should be the first, median, last point of segment in quadrant I.
Then, this V2SP macro will treat
pjf -> p3 

pjm -> p2

pjl -> p1

pif -> p4

pim -> p5

pil -> p6

Right?
then 

v should be the intersection point of l1 (p1,p2) and l2(p3,p4)

w should be the intersection point of l1 (p5,p6) and l2(p3,p4)

u should be the intersection point of l1 (p5,p6) and l2(p1,p2)

Agree?

**However**, in the TIP paper, the author wrote sth like

use the line passing the last (or first, depends on the quadrant) and middle points of one segment as l1, then use the line passing the last (or first, depends on the quadrant) and middle points of another segment (should be the diagonal corresponding quadrant).

This doesn't match.
Here, l1 passes the last and middle of one segment. l2 passes the first point of one segment and another first point of another segment...

I agree that you can still compute the CN score in this case. But it just doesn't match with the paper. 

Moreover, the author mentions only using segments from quadrant I and II, as well as segments from II and III to compute CN score and filter out segment tuples. However, in the code, they do the computation for 12 14 (124), 23 21 (231), 34 23 (342), 41 34 (413).

**Comment by mrliuxx** [comment]
@xiahaa I have different views from you, and I think your understanding of computing CN conic is a bit vague.

First, (p1, p2) and (p5, p6) are not on the same line. In your way, I think the correct one should be:
l1 should be determined by (p1, p2),
l2 should be determined by (p3, p4),
l3 should be determined by (p5, p6).
Then, l1, l2, and l3 intersect at points u, v, w. This is the form in the code, corresponding to points P1, P2, P3 in the paper.

I recommend that you observe Fig. 3 in the paper. Points u, v, w in the code correspond to points P1, P2, P3 in the paper; points p1 ... p6 in the code correspond to points {Qij} in the paper. You can follow the example in Fig. 3 and draw the calculation process in the `value4SixPoints()` function. You will understand how to calculate the CN of points p1 ... p6.

Second, Section III C of the paper only mentions the use of 123 quadrants to filter out segment tuples. But in fact, Section III A has divided the segment into four quadrants. So I think that only mentioning the 123 quadrant appears as an example, and in practice it needs to involve all segments in adjacent quadrants.
Therefore, every three adjacent quadrants (ie: 124, 231, 342, 413) are calculated in the code, and they use the same calculation method.

**Comment by xiahaa** [comment]
> aw the calculation process in the `value4SixPoints()` function. You will understand how to calculate the CN of points p1 ... p6.

First, I never said that 
> (p1, p2) and (p5, p6) are on the same line

You should refer to **Fig. 7. Construction of CNC based on two arcs**.
Fig3 is in the section where they introduce the general definition of CN score for nondegenerated conic.
Fig 7 and section 3.3 are where they introduce how they compute the CN score using arcs.

To your second point, please see that paper (quote from the paper, not rephrase)
> We only consider the combinations with arc segments from two adjacent quadrant sets, e.g., {ArcI , ArcII } and {ArcII , ArcIII }, but leave out those two-arc combinations from diagonal sets {ArcI , ArcIII } and {ArcII , ArcIV }. This choice further lowers down possible combinations, and more importantly
improves the robustness to calculate CNC values. As shown in Fig. 7, the lines Q (1)1 Q (2)1 and Q(1)3 Q(2) 3 are **likely to be parallel** for arcs from diagonal quadrant sets so that the intersection P1 does not exit, or lies quite far from the edge points. The calculation of CNC value is so instable that the determination of ellipse is no more effective. We exclude the combinations with arcs from two diagonal quadrant sets, avoiding this instability.

They do not use e.g. quadrants of I and III because those lines may be almost parallel (of course they need to compute lines according to section 3.3). 

By the way, theoretically, any six points on the ellipse should satisfy the CN conic constraint. So ideally, it doesn't matter if they compute the line according to 3.3 (Fig 7) or as they do in the code as long as those lines are NOT parallel.

So you could say if it is able to get the CN score as they do in the code right now. It is also ok to following Fig 7 to compute the lines and then the CN score. Both options are theoretically ok. It only matters for two points:
1. how the noise will affect the result? In other words, will one way be more stable than another?
2. It does not match with the paper (section 3.3 Fig 7).

**Comment by mrliuxx** [comment]
> They do not use e.g. quadrants of I and III because those lines may be almost parallel (of course they need to compute lines according to section 3.3).
By the way, theoretically, any six points on the ellipse should satisfy the CN conic constraint. So ideally, it doesn't matter if they compute the line according to 3.3 (Fig 7) or as they do in the code as long as those lines are NOT parallel.

Yes, I agree with you. Theoretically, any six points on the ellipse should satisfy the CN conic constraint, it's only necessary that their diagonal sides are not parallel.

**Comment by mrliuxx** [comment]
> They do not use e.g. quadrants of I and III because those lines may be almost parallel (of course they need to compute lines according to section 3.3).
By the way, theoretically, any six points on the ellipse should satisfy the CN conic constraint. So ideally, it doesn't matter if they compute the line according to 3.3 (Fig 7) or as they do in the code as long as those lines are NOT parallel.

Yes, I agree with you. Theoretically, any six points on the ellipse should satisfy the CN conic constraint, it's only necessary that their diagonal sides are not parallel.

But...excuse me, By the way, can I see the link to the article you read? Because through our communication, I feel that the articles we read are slightly different. The **"Fig. 7. Construction of CNC based on two arcs"** you mentioned is **"Fig. 4."** in my article. I'm not sure if there is any other difference between them. My article link is [https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7929406](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7929406).

Finally, I think the two ways you said are theoretically consistent. Maybe because of noise, the author determined the calculation method in the code through some experiments. It is only different from the examples in the paper.

**Comment by xiahaa** [comment]
> > They do not use e.g. quadrants of I and III because those lines may be almost parallel (of course they need to compute lines according to section 3.3).
> > By the way, theoretically, any six points on the ellipse should satisfy the CN conic constraint. So ideally, it doesn't matter if they compute the line according to 3.3 (Fig 7) or as they do in the code as long as those lines are NOT parallel.
> 
> Yes, I agree with you. Theoretically, any six points on the ellipse should satisfy the CN conic constraint, it's only necessary that their diagonal sides are not parallel.
> 
> But...excuse me, By the way, can I see the link to the article you read? Because through our communication, I feel that the articles we read are slightly different. The **"Fig. 7. Construction of CNC based on two arcs"** you mentioned is **"Fig. 4."** in my article. I'm not sure if there is any other difference between them. My article link is https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7929406.
> 
> Finally, I think the two ways you said are theoretically consistent. Maybe because of noise, the author determined the calculation method in the code through some experiments. It is only different from the examples in the paper.

For TIP, it is Fig 4, for arxiv, it is Fig 7.

It may be as you said.
That's why I say the code may be an experimental version. Especially, you will see a lot of MACROS of VS2P in the `tool.h`. Maybe they tried different combinations and then figure out the best one. Who knows. Only until the author replies can we have the answer.

**Comment by Li-Zhaoxi** [comment]
I have met the similar problems before. The result of this code is the same as that of the arxiv version.
I cannot contact the author that developed this code because he has graduated. 
So we can only adjust parameters to find the best result.  :(

**Comment by xiahaa** [comment]
> I have met the similar problems before. The result of this code is the same as that of the arxiv version.
> I cannot contact the author that developed this code because he has graduated.
> So we can only adjust parameters to find the best result. :(

ok. good to at least have some news from your side.
Then they may lose the advantages because the release version performs worse than that claimed in the paper.

**Comment by Li-Zhaoxi** [comment]
If you want to use this method as your comparison algorithm, you can use the results generated by this code.

This method is an extension of YAED. Also, the experiment proves that it performs better than YAED.

**Comment by xiahaa** [comment]
hi, thanks for your reply.
> you can use the results generated by this code.

For this, you mean copy and paste the results claimed in their paper?

Yeah, I know this code is an extension of YAED case I have compared their code and found quite a lot similar code.

**Comment by Li-Zhaoxi** [comment]
I mean that you can use this code to detect ellipses again, and use your evaluation code to calculate precision, recall and F-measure again. 

Currently, there is no general evaluation code, so the same detected results may obtain different recall,precision, and F-measure. I think it is meaningless to paste the results shown in paper directly.

**Comment by xiahaa** [comment]
> I mean that you can use this code to detect ellipses again, and use your evaluation code to calculate precision, recall and F-measure again.
> 
> Currently, there is no general evaluation code, so the same detected results may obtain different recall,precision, and F-measure. I think it is meaningless to paste the results shown in paper directly.

Thanks for your reply.
emm..... in this case, the result may not be very "fair" (I guess) for this CNC method...

But never mind, I will just do as you recommend case I have no time to finely tune their method.

Thanks.

**Comment by Li-Zhaoxi** [comment]
Hahahahaha, I guess the reviewer asked why the data didn't match this paper.

I gauss the author just forgot to submit the final version of this code.

It is not a big problem, you can explain that these results are generated by original code.

Good Luck !
